== Socket
* Network에서 정보가 전송되는 고유 식별자로 정의된다.
* 32비트 숫자로 지정, 짝수는 수신, 홀수는 송신이였으나 현재는 양방향 통신으로 가능하다
* Socket은 ARPA network를 통한 기계 간 통신을 위한 port의 식별자로 정의되었다.

=== Socket Type
.Datagram Sockets
* UDP
* Datagram socket에서 보내거나 받은 packet은 개별적으로 주소가 지정되고 라우팅됨.
* Datagram socket에서는 순서와 신뢰성이 보장되지 않으므로 한 기계 또는 프로세스에서 다른 기계로 전송되는 여러 packet이 임의의 순서로 도착하거나 전혀 도착하지 않을 수 있음

.Stream Sockets
* TCP
* SCTP
* DCCP
* 오류없는 데이터 전송, packet순서, 흐름 제어 보장
* 인터넷에서 일반적으로 TCP를 사용하여 구현되므로 응용 프로그램이 TCP/IP프로토콜을 사용하여 네트워크를 통해 실행될 수 있음
* 송신된 순서에 따라 중복되지 않게 데이터를 수신함으로 이에 따른 Overhead발생

.Raw Sockets
* 프로토콜별 전송 계층 형식 없이 IP packet을 직접 보내고 받을 수 있음
* 전송 계층 프로토콜에 상관없이 IP Packet으로 주고 받음
* Nmap과 같은 보안 관련 응용 프로그램에서 사용
* 일반적으로 네트워크 장비에서 사용할 수 있으며 IGMP와 OSPF와 같은 라우팅 프로토콜에 사용
* Ping 유틸리티에 의해 사용되는 인터넷 제어 메시지 프로토콜(ICMP)에도 사용

=== Socket통신
.Server Socket
* socket() 함수를 이용 소켓 생성
* bind() 함수를 이용해 대기 소켓의 IP, port 설정
* listen() 함수로 클라이언트 소켓 연결 대기
* Client socket 연결 요청이 오면 accept() 함수를 이용해 연결을 승인하고, 요청은 client socket과 통신을 위한 소켓을 생성
* Server socket은 listen() 함수를 통해 추가적인 연결 요청에 대비하고, 생성된 socket은 연결된 client socket과 데이터를 주고받음
* Client socket이나 생성된 socket을 닫으면 연결되어 있던 상대 socket도 닫힘

.Client Socket
* Client socket은 client 프로그램이나 server에서 생성할 수 있다. 위 server socket 설명에서 accept 후 새로운 socket이 생성되는데 이 또한 client socket으로 실질적인 socket 간 통신은 client socket 간에 이루어진다.
* socket() 함수를 이용하여 socket 생성
* connect() 함수를 이용해 지정된 sever에 연결 요청 전송
* Server에서 연결을 받아들이면 데이터 송수신 시작
* 데이터 송수신이 완료되거나 상대 socket의 닫힘이 감지되면 socket을 닫음

=== Server Socket
* accept() 함수를 통해 client의 연결을 기다리며, 연결에 성공한 경우 client와 통신을 위한 socket을 생성 반환

=== Computer Network
* 서로 데이터 교환, 리소스 공유 가능한 상호 연결된 Computing device의 집합
* 프로토콜을 사용 통신

=== Node
* Computing device간 메세지 전달을 위해 중간 연결 역할을 숭행하는 다양한 디바이스
하나 이상의 node가 다양한 형태로 연결될 수 있다.

.Node 종류
* Network Interface
* Repeater and hub
* Bridge
* Switch
* Router
* Modem
* Firewall

==== Network Interface
* 컴퓨터와 개인 또는 공용 네트워크 간 상호 연결 지점
* 일반적으로는 NIC(Network Interface Controller)와 같이 물리적인 디바이스를 이야기 하지만, Loopback interface와 같이 가상 디바이스로도 구현 가능

==== Network Interface Controller
* Network에 연결될 수 있도록 지원하는 하드웨어 장치

==== Repeater
* 장거리 전송 시 물리적인 영향 or 외부 영향에 따른 신호 품질 저하를 줄여줌
** 신호 증폭을 통해 장거리에 전송에 따른 신호 감소 문제 해결
** 노이즈 제거
* 물리적 매체를 변경 가능
** 장거리 대용량 데이터 전송 -> 광 기술
** 육지와 섬간 통신 -> 무선 통신

==== Hub
* Repeater와 동일 통신 거리 연장에 이용
* Repeater 1 : 1, Hub 1 : N 구조

==== bridge
* OSI model data link layer에서 동작
* 두 network segment를 연결 하나의 network로 동작
* 충돌 방지

==== Switch
* OSI model data link layer에서 동작
* Network간 packet전달에 이용
* Routing 정보를 이용해 패킷을 흘러갈 경로를 정할 수 있다

==== Modem
* Modulator-Demodulator에서 나온 단어로 디지털 데이터를 아날로그 신호로 변환 or 아날로그 신호를 디지털 데이터로 변환하는 역할을 한다

==== Firewall
* 네트워크 보안 및 액세스 규칙을 제어하기 위한 네트워크 장치 또는 소프트웨어
* 안전한 내부 네부터워크와 인터넷과 같이 잠재적으로 안전하지 않은 외부 네트워크 사이의 연결에 삽입
* 일반적으로 사전에 결정되지 않는 접근에 대해서는 차단을 기본

=== Protocol
* 네트워크 통해 정보를 교환하기 위한 일련의 규칙
* 연결 지향적일 수도 있고, 비연결 적을 수도 있고, 회선 모드나 패킷 전환을 사용할 수도 있고, 계층적 주소 지정이나 평면적 주소 지정을 사용할 수 있다.
* 프로토콜 스택의 중요한 예는 IEEE 802.11 (Wi-Fi 프로토콜 )과 IP(인터넷 프로토콜)를 통한 TCP 를 통해 실행되는 HTTP (WWW protocol) 이다.


=== Network 계층

.Collision Avoidance(충돌 회피)
* 공유데이터 환경에서 여러 기기가 동시에 데이터를 전송하려고 할 때 충돌이 발생할 수 있다.
* Carrier Sense Multiple Access with Collision Detection (CSMA/CD) 또는 Carrier Sense Multiple Access with Collision Avoidance (CSMA/CA)와 같은 프로토콜은 네트워크에서 충돌을 피하도록 도와준다.

.Digital to Analog Conversion(디지털 아날로그 변환)
* 디지털 데이터는 컴퓨터에서 처리되지만, 구리선 또는 광섬유와 같은 물리적 매체를 통해 전송하기 위해 아날로그 신호로 변환되어야 한다.

.Error Detection and Correction(오류 감지와 수정)
* 전송 중 간섭에 의해 손상될 수 있다.
* 체크섬, 패리티 비트 및 Reed-Solomon 코드와 같은 오류 감지 및 수정 기술을 사용하여 데이터 무결성을 보장한다.

.Routing(경로 지정)
* OSPF, BGP, 또는 RIP와 같은 경로 지정 프로토콜은 데이터 패킷이 효율적으로 목적지에 도달하기 위한 최적 경로를 결정하는 데 사용된다.

.Operating System Compatibility(운영 체제 호환성)
* 네트워크 소프트웨어는 네트워크의 다양한 장치가 다른 운영 체제를 사용할 수 있기 때문에 다른 운영 체제와 호환되어야 한다.
* 이 호환성은 이질적인 시스템 간에 데이터가 원활하게 전송될 수 있도록 보장한다.

.Heterogeneous Network Cabling(이질적인 네트워크 케이블링)*
* 네트워크는 Ethernet, Wi-Fi, 광섬유 등과 같은 다양한 종류의 케이블을 포함한 다양한 물리적 인프라를 가질 수 있다.
* 네트워크 소프트웨어는 이러한 차이를 처리하고 사용된 케이블링의 특성에 적응해야 한다.

.Network Protocols(네트워크 프로토콜)
* 다양한 네트워크 프로토콜은 데이터의 구조, 전송 및 수신 방식을 규정한다.
* 이러한 프로토콜은 TCP/IP, UDP, HTTP, FTP 등이 포함될 수 있다.
* 네트워크 소프트웨어는 이러한 프로토콜을 구현하여 호환성과 신뢰성 있는 데이터 전송을 보장한다.

.Security(보안)
* 네트워크 소프트웨어는 데이터 전송 중 보안 문제도 다루어야 한다.
* 데이터의 안전한 전송을 위한 암호화, 통신 당사자의 신원을 확인하기 위한 인증, 무단 접근 및 데이터 침입을 방지하기 위한 다양한 보안 프로토콜이 포함된다.

.Quality of Service(QoS - 서비스 품질)
* 일부 데이터는 실시간 통신에서 음성 또는 비디오 데이터와 같이 우선 처리를 필요로 할 수 있다.
QoS 메커니즘은 네트워크에서 중요한 데이터가 우선 처리되도록 보장한다.

.Scalability(확장성)
* 네트워크가 성장함에 따라 소프트웨어는 증가하는 데이터 트래픽 및 장치 연결을 수용하기 위해 효율적으로 확장 가능해야 한다.

.OSI Model
* Physical Layer: 이 계층은 실제 데이터 전송을 다룹니다(전선, 광섬유 등). 하드웨어 특성, 신호 및 전송 속도를 정의한다.

* Data Link Layer계층: 이 계층은 직접 연결된 두 노드 간의 신뢰할 수 있는 링크를 만듭니다. 프레임 형식, 오류 감지 및 흐름 제어와 같은 문제를 처리한다. Ethernet은 데이터 링크 계층 기술의 예입니다.

* Network Layer: 네트워크 계층은 다중 연결된 네트워크를 통해 패킷을 출발지에서 목적지로 라우팅한다. IP(Internet Protocol)가 이 계층에서 작동한다.

* Transport Layer: 이 계층은 발신자와 수신자 간의 종단 간 통신을 보장한다. 데이터 분할, 흐름 제어 및 오류 정정을 관리한다. TCP(Transmission Control Protocol) 및 UDP(User Datagram Protocol)는 전송 계층 프로토콜입니다.

* Session Layer: 이 계층은 통신 세션을 설정, 관리 및 종료한다. 세션 동기화 및 대화 제어를 처리한다.

* Presentation Layer: 데이터 번역, 압축 및 암호화를 담당한다. 데이터가 발신자와 수신자 양쪽에서 읽을 수 있는 형식으로 제공됨을 보장한다.

* Application Layer: 가장 상위 계층으로 응용 프로그램별 프로토콜 및 데이터 형식을 처리한다. 웹 브라우저, 이메일 클라이언트 및 파일 전송 소프트웨어와 같은 사용자 수준 응용 프로그램이 작동하는 곳입니다.

== DNS
* 컴퓨터 네트워크에서 사용되는 계층화된 분산 데이터베이스 시스템이다. DNS의 주요 목적은 사람이 이해할 수 있는 도메인 이름(예: www.example.com)을 컴퓨터가 이해할 수 있는 IP 주소(예: 192.168.1.1)로 변환하거나 그 반대로 IP 주소를 도메인 이름으로 변환하는 것이다.

* 도메인 이름 해석 (Name Resolution): DNS는 사용자가 입력한 도메인 이름을 해당 도메인에 대한 IP 주소로 해석합니다. 이것은 웹 브라우징, 이메일 통신, 파일 공유 및 다른 네트워크 활동에서 중요한 역할을 합니다.

* 계층 구조: DNS는 계층 구조를 가지고 있으며, 최상위 수준의 도메인(TLD, Top-Level Domain)에서부터 하위 수준 도메인(subdomain)까지 내려가는 방식으로 도메인 이름을 구성합니다. 예를 들어, "www.example.com"에서 ".com"은 최상위 수준 도메인이고 "example.com"은 하위 수준 도메인입니다.

* DNS 서버: DNS 정보는 전 세계에 분산된 DNS 서버에 저장되어 있으며, 이들은 계층적인 구조를 가집니다. 루트 서버, 최상위 도메인 서버, 중간 도메인 서버 및 기업 또는 ISP(인터넷 서비스 제공업체)의 로컬 DNS 서버 등이 있습니다.

* DNS 쿼리: 컴퓨터 또는 장치가 도메인 이름을 IP 주소로 변환하려면 DNS 쿼리를 보내야 합니다. 이 쿼리는 사용자 요청에 따라 로컬 DNS 서버 또는 상위 DNS 서버로 전달되고, 최종적으로 도메인에 대한 IP 주소를 반환합니다.

* DNS 캐싱: DNS 서버는 이전에 검색한 도메인 이름에 대한 결과를 캐싱하여 빠른 응답을 제공합니다. 이를 통해 동일한 도메인 이름에 대한 반복적인 쿼리를 줄일 수 있습니다.

* 레코드 타입
** A: 도메인에 대한 IP 응답
** NS: 특정 도메인의 Name Server 정보 응답
** CNAME: canonical name 설정
** MX: 도메인의 메일 수신 서버 주소를 응답
** TXT: 임의 문자열 부가 정보 관리, SPF, DKIM 용으로도 사용
*** https://en.wikipedia.org/wiki/TXT_record
** SRV: IP 외에 Port 번호까지 서비스 가능
*** https://en.wikipedia.org/wiki/SRV_record
* 부하 분산
** 하나의 도메인에 여러개의 IP 를 등록할 수 있음
** 클라이언트는 응답 받은 여러 IP 중 하나를 사용함.

=== DNS Query Flow
* Local DNS 에 캐싱이 되어 있는 경우는 바로 응답
* 캐싱이 되어 있지 않은 경우에
  * ROOT DNS, TLD DNS, Authoratative DNS 순서로 질의하여 결과 응답

== L7 Application Layer
* 데이터를 사용자에게 전달하는 계층

* 하위 세 개의 계층(Host-to-Network, Internet, Transport)은 모두 데이터가 한 컴퓨터에서 다른 컴퓨터로 어떻게 전송되는지를 정의하는 데 협력한다.

* Application layer은 데이터가 전송된 후에 어떻게 처리할지를 결정한다.

* 다양한 application layer protocol이 있다
** 웹을 위한 HTTP,
** 이메일을 위한 SMTP, POP, IMAP
** 파일 전송을 위한 FTP, FSP, TFTP
** 파일 접근을 위한 NFS
** 파일 공유를 위한 Gnutella와 BitTorrent
** 음성 통신을 위한 Session Initiation Protocol (SIP) 및 Skype 등이 있다. 

* 필요한 경우 고유한 application layer protocol을 정의할 수 있다.
** Skype protocol은 기본적으로 P2P architecture를 기반으로 하며, 사용자 간의 음성 통화, 비디오 통화, 메시지 전송 등을 가능하게 한다. 
** Skype의 특성 및 보안 요구 사항을 충족하기 위해 개발되었다.
** Skype만의 위한 비공개 protocol

== Transport Layer
* 이 수준에서는 두 가지 주요 프로토콜이 있다.

* Transmission Control Protocol (TCP)이 있는데, 이는 높은 오버헤드 프로토콜로서 손실된 데이터나 손상된 데이터의 재전송 및 전송된 바이트의 순서대로 전달을 허용한다.

* User Datagram Protocol (UDP)로, 수신자는 손상된 패킷을 감지할 수 있지만 패킷이 올바른 순서로 전달되는 것을 (또는 아예 전달되는 것을) 보장하지 않는다. 그러나 UDP는 종종 TCP보다 빠르다. TCP는 신뢰성 있는 프로토콜로, UDP는 신뢰성 없는 프로토콜이다. 나중에 신뢰성 없는 프로토콜이 앞서 이야기한 것보다 훨씬 유용하다는 것을 보게 될 것이다.

=== UDP
* checksum 정도만 제공
** 보내는 패킷의 데이터가 전송 도중 잘못 되었는지 체크만 함
[source,cosole]
----
Format

                                    
                  0      7 8     15 16    23 24    31  
                 +--------+--------+--------+--------+ 
                 |     Source      |   Destination   | 
                 |      Port       |      Port       | 
                 +--------+--------+--------+--------+ 
                 |                 |                 | 
                 |     Length      |    Checksum     | 
                 +--------+--------+--------+--------+ 
                 |                                     
                 |          data octets ...            
                 +---------------- ...                 

                      User Datagram Header Format
----

== TCP

* 출발지 포트번호, 목적지 포트번호
* 세그먼트가 목적지에 도착하면, OS 는 목적지 포트번호로 애플리케이션(프로세스)을 식별
** 해당 애플리케이션에 전달.

[source,cosole]
----
  TCP Header Format

                                    
    0                   1                   2                   3   
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |          Source Port          |       Destination Port        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                        Sequence Number                        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                    Acknowledgment Number                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |  Data |           |U|A|P|R|S|F|                               |
   | Offset| Reserved  |R|C|S|S|Y|I|            Window             |
   |       |           |G|K|H|T|N|N|                               |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |           Checksum            |         Urgent Pointer        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                    Options                    |    Padding    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             data                              |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

                            TCP Header Format

          Note that one tick mark represents one bit position.
----
*from. RFC793 TRANSMISSION CONTROL PROTOCOL*

== Well-Known 포트
* 고정 포트번호
* HTTP 80
* DNS 53
* SMTP 25

== TCP 전송계층
- Sequence Number - 순서번호
- Acknowledge Number - 어디까지 잘 받았는지, 다음 번 보낼 패킷의 Sequence Number 를 응답
- Flags
  - ACK
  - RST
  - SYN
  - FIN
- Window Size

== 데이터 재전송

=== 수신측
* 수신한 패킷의 ACK 를 전송

=== 송신측
* 특정 시간(타이머!)동안 보낸 패킷에 대한 ACK 패킷이 없는 경우 retransmission.

* 송신 패킷이 전달이 안된 경우.

* 수신 입장에선 적장한 패킷을 받음. 정상 케이스 -

* 수신(ACK) 패킷이 전달이 안된 경우.

* 수신 입장에선 같은 패킷을 두 번 받음. 같은 패킷에 대해 다시 ACK

== 데이터 재전송
=== 수신측
* 수신한 패킷의 ACK 를 전송
* 중간 누락 패킷이 있는 경우, 순서가 맞는 마지막 패킷의 ACK를 계속 전송

=== 송신측
* Duplicated ACK가 3번 오면 재전송

=== Time_WAIT
* TIME_WAIT는 TCP의 4-Way Handshaking 과정을 통한 소켓 종료 과정 중의 상태이다.

* TIME_WAIT 상태가 되는 조건은 자신이 종료를 위해 FIN패킷을 보내고 그에 대한 응답으로 ACK 패킷을 받는다. 그런 다음 상대방의 FIN 패킷을 받고 그에 대한 응답으로 ACK 패킷을 보내고 TIME_WAIT가 된다.

* TIME_WAIT 상태는 2MSL 대기 상태(2MSL wait status)라고도 하는데, 여기서 MSL(Maximum Segment Lifttime)이란 패킷이 폐기되기 전에 네트워크에서 살아있을 수 있는 시간을 말한다.

* 모든 IP패킷은 TTL(time-to-live)라는 값을 가지는데 이 값이 0이 되면 해당 패킷은 폐기된다. 모든 라우터는 패킷을 통과시키면서 이 TTL값을 1만큼 감소시킨다.

* 소켓이 TIME_WAIT 상태가 되면 MSL의 두배만큼의 시간동안 TIME_WAIT상태를 유지한다. 이로 인해 ACK 패킷이 TTL에 의해 소실되어도 ACK패킷을 재전송하여 FIN패킷이 재선송될 수 있다. TIME_WAIT상태가 끝나면 소켓은 CLOSED상태가 된다.

.TIME_WAIT가 필요한 이유
* (1) 지연 패킷 문제 : 송신한 데이터를 모두 수신하기 전에 새로운 연결이 이미 진행되었다면 송신한 데이터, 즉 지연 패킷이 뒤늦게 도착해 문제가 발생한다. 드문 경우이지만 SEQ까지 동일하다면 데이터 무결성에도 문제가 생긴다.
* (2) 연결 종료 문제 : 마지막 ACK 손실 시, 상대방은 LAST_ACK 상태에 빠지게 된다. 따라서 새로운 연결을 위해 SYN패킷을 보내도 RST를 리턴하며 실패한다.

==== Flow Control
* TCP 헤더의 윈도우 크기
* 수신측에서 수신 가능한 버퍼의 크기, 해당 크기에 맞게 데이타를 보내면 됨
* 수신 애플리케이션의, 데이타 수신 속도와 관계가 있음.
* netstat 으로 확인 가능.

==== Congestion Control
* flow control 과는 다름
* network 의 문제 (도로의 문제 )
* 네트워크는 명시적으로 혼잡도를 알려주지 않음. ^^;
* TCP 가 열심히 추측해야 함.
* 네트워크 상황이 나쁜데, TCP 패킷이 쏟아지면 …​
* 상황이 악화됨 - retransmission

==== Congestion Control
* 혼잡제어 윈도우 활용
* CWND - 한번에 ACK 없이 보낼 수 있는 세그먼트의 숫자
* ss -i 명령으로 확인 가능
* ACK 없이 보낼 수 있는 패킷의 수
* 프로토콜 상에 드러나지 않는 값.
* 송신측에서 제어

